/**:
  ros__parameters:
    use_sim_time: true

    # Enable only 2D LiDAR
    subscribe_scan:      true
    scan_topic:          "/scan"
    qos_scan:            1

    # Disable all other inputs
    subscribe_depth:     false
    subscribe_rgb:       false
    subscribe_stereo:    false
    subscribe_scan_cloud: false
    subscribe_user_data: false
    subscribe_odom_info: false

    # Frames
    frame_id:            base_link
    map_frame_id:        map
    odom_frame_id:       ""   # turns off odom→base TF

    
